services:
  - type: web
    name: weather-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn weather_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: weather-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: OPENWEATHER_API_KEY
        sync: false

databases:
  - name: weather-db
    databaseName: weather_db
    user: weather_user
    plan: free
